# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

# On Towaki's machine with a RTX8000 on the spot model, this code takes:
# 20 seconds per epoch
# 13:37 script runtime as reported on tensorboard
# 41.6 IOU at final evaluation

# On Towaki's machine with a RTX8000 on the clock model, this code takes:
# 20 seconds per epoch
# 13:37 script runtime as reported on tensorboard
# 41.6 IOU at final evaluation

global:
    exp_name: 'test-triplanar-sdf'

optimizer:
    optimizer_type: 'adam'
    lr: 0.001
    grid_lr_weight: 1.0

dataset:
    num_samples: 500000      # Number of samples held in dataset during training
    dataset_type: 'sdf'
    num_samples_on_mesh: 100000000  # Number of samples generated on mesh surface to initialize the occupancy grid

renderer:
    tracer_type: 'PackedSDFTracer'
    num_steps: 256
    render_batch: 0
    step_size: 0.8
    camera_origin:
        - -2.8
        - 2.3
        - -2.8
    shading_mode: 'matcap'
    render_res:
        - 1024
        - 1024
    shadow: True

trainer:
    trainer_type: 'SDFTrainer'
    epochs: 10
    batch_size: 512
    model_format: 'full'
    valid_every: 20
    save_every: 5
    render_tb_every: 5
    log_2d: True
    only_last: True
    resample: True

grid:
    grid_type: 'TriplanarGrid'
    interpolation_type: 'linear'
    multiscale_type: 'sum'
    feature_dim: 4
    feature_std: 0.01
    base_lod: 5

net:
    nef_type: 'NeuralSDF'
    hidden_dim: 128
    num_layers: 1
    out_dim: 1
    position_input: True

embedder:
    embedder_type: 'none'
